### ISSUE TITLE
todo : Complete the  Decoder Class 

### ISSUE THREAD

**Issue by Shreyasvaidya** [AISocietyIITJ/NNIT#2]
DEtR style architecture with self-attention and cross-attentions layers ,will return the vector representation of the predicted sentence
path - 'model/decoder.py'
Minimum assignees -3
Maximum Assignees - 5

**Comment by Jay18Mehta** [comment]
interested

**Comment by yorozuya-2003** [comment]
Interested

**Comment by VinayVaishnav** [comment]
interested

**Comment by introspective-321** [comment]
Interested

**Comment by introspective321** [comment]
Interested

**Comment by onkar-singh-rajput-23** [comment]
Interested
