### ISSUE TITLE
todo: Complete the load data function in load_data.py

### ISSUE THREAD

**Issue by Shreyasvaidya** [AISocietyIITJ/NNIT#3]
Given the path to directory containing the images, the function should return the dataloader which can be fed exactly in the vit architecture
Minimum assignees -2 
Maximum assignees - 3

**Comment by rohit85bajaj** [comment]
Interested

**Comment by rahulsharma6969** [comment]
Interested

**Comment by Parisharma16** [comment]
interested

**Comment by dhruvak001** [comment]
Interested
